import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  header: { backgroundColor: '#065A82', padding: 20 },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  headerTitle: { color: '#fff', fontSize: 24, fontWeight: 'bold' },
  headerSubtitle: { color: '#A8DADC', fontSize: 14, marginTop: 4 },
  userInfo: { color: '#A8DADC', fontSize: 13, marginTop: 8 },
  btnLogout: { backgroundColor: 'rgba(255,255,255,0.15)', paddingHorizontal: 14, paddingVertical: 6, borderRadius: 6, borderWidth: 1, borderColor: 'rgba(255,255,255,0.3)' },
  btnLogoutText: { color: '#fff', fontWeight: '600', fontSize: 13 },
  authContainer: { flex: 1, justifyContent: 'center', padding: 20 },
  authBox: { backgroundColor: '#fff', borderRadius: 12, padding: 24, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 12, elevation: 4 },
  authTitle: { fontSize: 22, fontWeight: 'bold', color: '#065A82', textAlign: 'center', marginBottom: 24 },
  authToggle: { textAlign: 'center', marginTop: 20, color: '#666', fontSize: 14 },
  authLink: { color: '#065A82', fontWeight: '600' },
  nav: { flexDirection: 'row', padding: 10, gap: 10, backgroundColor: '#f5f5f5' },
  navBtn: { flex: 1, padding: 10, borderRadius: 8, backgroundColor: '#ddd', alignItems: 'center' },
  navBtnActive: { backgroundColor: '#065A82' },
  navText: { color: '#333', fontWeight: '600' },
  navTextActive: { color: '#fff' },
  form: { padding: 20 },
  formTitle: { fontSize: 18, fontWeight: 'bold', color: '#065A82', marginBottom: 15 },
  input: { borderWidth: 1, borderColor: '#ccc', borderRadius: 8, padding: 12, marginBottom: 12, fontSize: 14 },
  textarea: { height: 100, textAlignVertical: 'top' },
  btnEnviar: { backgroundColor: '#028090', padding: 15, borderRadius: 8, alignItems: 'center' },
  btnEnviarText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
  lista: { padding: 15 },
  empty: { textAlign: 'center', color: '#888', marginTop: 20 },
  card: { backgroundColor: '#f0f9fb', borderRadius: 10, padding: 15, marginBottom: 12, borderLeftWidth: 5, borderLeftColor: '#065A82' },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  cardTipo: { fontSize: 16, fontWeight: 'bold', color: '#065A82' },
  btnEliminar: { color: '#e74c3c', fontWeight: '600' },
  cardDesc: { color: '#333', marginTop: 5 },
  cardSector: { color: '#888', fontSize: 12, marginTop: 5 },

  // New styles
  statBox: { flex: 1, backgroundColor: 'white', borderRadius: 10, padding: 16, alignItems: 'center', borderWidth: 1, borderColor: '#e5e7eb' },
  statNumber: { fontSize: 28, fontWeight: '800', color: '#065A82' },
  statLabel: { fontSize: 10, color: '#6b7280', marginTop: 4, textTransform: 'uppercase', letterSpacing: 0.5 },
  recentCard: { backgroundColor: 'white', borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 8, padding: 12, marginBottom: 8 },
  badge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 100 },
  badgePending: { backgroundColor: '#fef3c7' },
  badgeReview: { backgroundColor: '#dbeafe' },
  badgeResolved: { backgroundColor: '#dcfce7' },
  tipoSelect: { borderWidth: 1, borderColor: '#ccc', borderRadius: 8, padding: 12, marginBottom: 12, fontSize: 14 },
});
