import { StyleSheet, Platform } from 'react-native';

const neumorphic = Platform.select({
  ios: {
    shadowColor: '#c8d0dc',
    shadowOffset: { width: 7, height: 7 },
    shadowOpacity: 1,
    shadowRadius: 14,
  },
  android: { elevation: 6 },
});

const neumorphicSmall = Platform.select({
  ios: {
    shadowColor: '#c8d0dc',
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 1,
    shadowRadius: 10,
  },
  android: { elevation: 4 },
});

const neumorphicInset = Platform.select({
  ios: {
    shadowColor: '#c8d0dc',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 1,
    shadowRadius: 7,
  },
  android: { elevation: -2 },
});

export const COLORS = {
  bg: '#e4ebf5',
  card: '#e8eef6',
  primary: '#065A82',
  primaryLight: '#028090',
  primaryDark: '#043e5c',
  danger: '#dc2626',
  warning: '#d97706',
  success: '#16a34a',
  text: '#2d4059',
  textSecondary: '#7a8ba8',
  textMuted: '#a0b0c8',
  shadowLight: '#ffffff',
  shadowDark: '#c8d0dc',
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },

  header: {
    backgroundColor: COLORS.primary,
    paddingTop: Platform.OS === 'ios' ? 50 : 36,
    paddingBottom: 14,
    paddingHorizontal: 20,
  },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  headerTitle: { color: '#fff', fontSize: 20, fontWeight: '700', letterSpacing: -0.5 },
  headerSubtitle: { color: '#A8DADC', fontSize: 14, marginTop: 2 },
  userInfo: { color: '#A8DADC', fontSize: 13, marginTop: 8 },
  btnLogout: {
    backgroundColor: 'rgba(255,255,255,0.12)',
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 100,
  },
  btnLogoutText: { color: '#fff', fontWeight: '600', fontSize: 13 },

  authContainer: { flex: 1, justifyContent: 'center', padding: 20, backgroundColor: COLORS.bg },
  authBox: {
    backgroundColor: COLORS.card,
    borderRadius: 14,
    padding: 28,
    ...neumorphic,
  },
  authTitle: { fontSize: 24, fontWeight: '700', color: COLORS.primary, textAlign: 'center', marginBottom: 24 },
  authToggle: { textAlign: 'center', marginTop: 20, color: COLORS.textSecondary, fontSize: 14 },
  authLink: { color: COLORS.primary, fontWeight: '600' },
  authError: {
    backgroundColor: 'rgba(220,38,38,0.07)',
    color: COLORS.danger,
    fontSize: 14,
    textAlign: 'center',
    padding: 10,
    borderRadius: 10,
    marginBottom: 12,
  },

  nav: {
    flexDirection: 'row',
    padding: 8,
    gap: 8,
    backgroundColor: COLORS.bg,
  },
  navBtn: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 10,
    backgroundColor: COLORS.card,
    alignItems: 'center',
    ...neumorphicSmall,
  },
  navBtnActive: { backgroundColor: COLORS.primary },
  navText: { color: COLORS.textSecondary, fontWeight: '600', fontSize: 12 },
  navTextActive: { color: '#fff' },

  form: { padding: 20, backgroundColor: COLORS.bg, flex: 1 },
  formTitle: { fontSize: 26, fontWeight: '700', color: COLORS.text, marginBottom: 20, letterSpacing: -0.3 },
  formLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  input: {
    backgroundColor: COLORS.card,
    borderRadius: 10,
    padding: 14,
    marginBottom: 16,
    fontSize: 14,
    color: COLORS.text,
    ...neumorphicInset,
  },
  textarea: { height: 110, textAlignVertical: 'top' },
  select: {
    backgroundColor: COLORS.card,
    borderRadius: 10,
    padding: 14,
    marginBottom: 16,
    fontSize: 14,
    color: COLORS.text,
    ...neumorphicInset,
  },
  btnEnviar: {
    backgroundColor: COLORS.primary,
    padding: 16,
    borderRadius: 10,
    alignItems: 'center',
    ...neumorphicSmall,
  },
  btnEnviarText: { color: '#fff', fontWeight: '700', fontSize: 16 },

  lista: { padding: 16, backgroundColor: COLORS.bg, flex: 1 },
  empty: { textAlign: 'center', color: COLORS.textMuted, marginTop: 20, fontSize: 14 },

  card: {
    backgroundColor: COLORS.card,
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
    ...neumorphic,
  },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  cardTipo: { fontSize: 12, fontWeight: '600', color: COLORS.text },
  btnEliminar: { color: COLORS.danger, fontWeight: '600', fontSize: 12 },
  cardDesc: { color: COLORS.text, marginTop: 8, fontSize: 15, fontWeight: '500' },
  cardSector: { color: COLORS.textSecondary, fontSize: 13, marginTop: 4 },
  cardAuthor: { color: COLORS.textMuted, fontSize: 12, marginTop: 4 },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.04)',
  },

  statBox: {
    flex: 1,
    backgroundColor: COLORS.card,
    borderRadius: 14,
    padding: 20,
    alignItems: 'center',
    ...neumorphic,
  },
  statNumber: { fontSize: 32, fontWeight: '800', color: COLORS.primary, letterSpacing: -1 },
  statLabel: {
    fontSize: 11,
    color: COLORS.textSecondary,
    marginTop: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    fontWeight: '600',
  },

  recentCard: {
    backgroundColor: COLORS.card,
    borderRadius: 10,
    padding: 16,
    marginBottom: 8,
    ...neumorphicSmall,
  },

  badge: { paddingHorizontal: 12, paddingVertical: 4, borderRadius: 100 },
  badgeText: { fontSize: 11, fontWeight: '700', textTransform: 'capitalize' },
  badgePending: { backgroundColor: '#fef3c7' },
  badgePendingText: { color: '#92400e' },
  badgeReview: { backgroundColor: '#dbeafe' },
  badgeReviewText: { color: '#1e40af' },
  badgeResolved: { backgroundColor: '#dcfce7' },
  badgeResolvedText: { color: '#166534' },

  tipoBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6 },
  tipoSeguridad: { backgroundColor: '#fee2e2' },
  tipoInfraestructura: { backgroundColor: '#fef3c7' },
  tipoMovilidad: { backgroundColor: '#dbeafe' },
  tipoAmbiental: { backgroundColor: '#dcfce7' },
  tipoSalud: { backgroundColor: '#f3e8ff' },
  tipoEducacion: { backgroundColor: '#e0e7ff' },
  tipoOtro: { backgroundColor: '#e5e7eb' },

  tipoSelect: {
    backgroundColor: COLORS.card,
    borderRadius: 10,
    padding: 14,
    marginBottom: 16,
    fontSize: 14,
    color: COLORS.text,
    ...neumorphicInset,
  },

  pageHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  pageTitle: { fontSize: 26, fontWeight: '700', color: COLORS.text, letterSpacing: -0.3 },
  pageSubtitle: { fontSize: 14, color: COLORS.textSecondary },

  filterBar: { flexDirection: 'row', gap: 10, marginBottom: 20, flexWrap: 'wrap' },
  filterInput: {
    flex: 1,
    minWidth: 120,
    backgroundColor: COLORS.card,
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    color: COLORS.text,
    ...neumorphicInset,
  },

  btnPrimary: {
    backgroundColor: COLORS.card,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 10,
    ...neumorphicSmall,
  },
  btnPrimaryText: { color: COLORS.primary, fontWeight: '700', fontSize: 14 },

  btnAccent: {
    backgroundColor: COLORS.primaryLight,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 10,
    ...neumorphicSmall,
  },
  btnAccentText: { color: '#fff', fontWeight: '700', fontSize: 14 },

  btnDanger: {
    backgroundColor: COLORS.danger,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 10,
    ...neumorphicSmall,
  },
  btnDangerText: { color: '#fff', fontWeight: '700', fontSize: 14 },

  btnSm: { paddingHorizontal: 12, paddingVertical: 8 },
  btnSmText: { fontSize: 12 },

  detailCard: {
    backgroundColor: COLORS.card,
    borderRadius: 14,
    padding: 24,
    margin: 16,
    ...neumorphic,
  },
  detailHeader: { flexDirection: 'row', gap: 10, marginBottom: 16 },
  detailTitle: { fontSize: 22, fontWeight: '700', color: COLORS.text, marginBottom: 20, letterSpacing: -0.2 },
  detailMeta: { marginBottom: 24 },
  detailMetaItem: { marginBottom: 14 },
  detailLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: COLORS.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
    marginBottom: 2,
  },
  detailValue: { fontSize: 15, fontWeight: '500', color: COLORS.text },
  detailActions: {
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.05)',
    gap: 12,
  },

  commentSection: { marginTop: 24 },
  commentTitle: { fontSize: 16, fontWeight: '700', color: COLORS.text, marginBottom: 12 },
  commentCard: {
    backgroundColor: COLORS.card,
    borderRadius: 10,
    padding: 16,
    marginBottom: 10,
    ...neumorphicSmall,
  },
  commentHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 6 },
  commentAuthor: { fontSize: 14, fontWeight: '700', color: COLORS.text },
  commentDate: { fontSize: 12, color: COLORS.textMuted, marginLeft: 'auto' },
  commentText: { fontSize: 14, color: COLORS.textSecondary, lineHeight: 20 },

  roleBadge: { paddingHorizontal: 10, paddingVertical: 3, borderRadius: 100 },
  roleCiudadano: { backgroundColor: '#dbeafe' },
  roleAutoridad: { backgroundColor: '#dcfce7' },
  roleAdministrador: { backgroundColor: '#fee2e2' },
  roleBadgeText: { fontSize: 12, fontWeight: '700' },

  perfilCard: {
    backgroundColor: COLORS.card,
    borderRadius: 14,
    padding: 36,
    margin: 16,
    alignItems: 'center',
    ...neumorphic,
  },
  perfilAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 28,
  },
  perfilAvatarText: { color: '#fff', fontSize: 32, fontWeight: '700' },
  perfilRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.04)',
  },
  perfilLabel: { color: COLORS.textSecondary, fontSize: 14 },
  perfilValue: { color: COLORS.text, fontSize: 14, fontWeight: '600' },

  adminTable: {
    backgroundColor: COLORS.card,
    borderRadius: 14,
    margin: 16,
    overflow: 'hidden',
    ...neumorphic,
  },
  adminTableRow: {
    flexDirection: 'row',
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.03)',
    alignItems: 'center',
  },
  adminTableHeader: {
    backgroundColor: 'rgba(0,0,0,0.02)',
  },
  adminTableHeaderText: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  adminTableCell: { flex: 1, fontSize: 14, color: COLORS.text },
  adminTableCellName: { fontWeight: '600' },
  adminTableCellEmail: { color: COLORS.textSecondary },
  adminTableCellDate: { fontSize: 12, color: COLORS.textMuted },

  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: COLORS.bg },
});
